version: '3.1'

services:

  psql-db:
    image: postgres
    ports:
      - ${POSTGRES_PORT_EXTERNAL}:5431
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - psql-db-data:/var/lib/postgresql/data
    networks:
      - ws-network

volumes:
  psql-db-data:

networks:
  ws-network: